enum Commands {
  abor('ABOR'),
  acct('ACCT'),
  adat('ADAT'),
  allo('ALLO'),
  appe('APPE'),
  auth('AUTH'),
  avbl('AVBL'),
  ccc('CCC'),
  cdup('CDUP'),
  conf('CONF'),
  csid('CSID'),
  cwd('CWD'),
  dele('DELE'),
  dsiz('DSIZ'),
  enc('ENC'),
  eprt('EPRT'),
  epsv('EPSV'),
  feat('FEAT'),
  help('HELP'),
  host('HOST'),
  lang('LANG'),
  list('LIST'),
  lprt('LPRT'),
  lpsv('LPSV'),
  mdtm('MDTM'),
  mfct('MFCT'),
  mff('MFF'),
  mfmt('MFMT'),
  mic('MIC'),
  mkd('MKD'),
  mlsd('MLSD'),
  mlst('MLST'),
  mode('MODE'),
  nlst('NLST'),
  noop('NOOP'),
  opts('OPTS'),
  pass('PASS'),
  pasv('PASV'),
  pbsz('PBSZ'),
  port('PORT'),
  prot('PROT'),
  pwd('PWD'),
  quit('QUIT'),
  rein('REIN'),
  rename('RNFR'),
  rest('REST'),
  retr('RETR'),
  rmd('RMD'),
  rmda('RMDA'),
  rnfr('RNFR'),
  rnto('RNTO'),
  site('SITE'),
  size('SIZE'),
  smnt('SMNT'),
  spsv('SPSV'),
  stat('STAT'),
  stor('STOR'),
  stou('STOU'),
  stru('STRU'),
  syst('SYST'),
  thmb('THMB'),
  type('TYPE'),
  user('USER'),
  xcup('XCUP'),
  xmkd('XMKD'),
  xpwd('XPWD'),
  xrcp('XRCP'),
  xrmd('XRMD'),
  xrsq('XRSQ'),
  xsem('XSEM'),
  xsen('XSEN');

  final String command;

  const Commands(this.command);

  static Commands get(String command) {
    return Commands.values.firstWhere(
      (e) => e.command == command,
      orElse: () => throw ArgumentError('Invalid command: $command'),
    );
  }
}
